#!/bin/sh

if [ -f /etc/conf.d/logrotate ]; then
	. /etc/conf.d/logrotate
fi

_cpulimit=""
if [ -x /usr/bin/cpulimit ] && [ -n "${LOGROTATE_CPULIMIT}" ]; then
	_cpulimit="/usr/bin/cpulimit --limit=${LOGROTATE_CPULIMIT}"
fi

${_cpulimit} /usr/sbin/logrotate --state=/data/logs/logrotate.status /etc/logrotate.conf
ExitValue=$?
if [ ${ExitValue} != 0 ]; then
	/usr/bin/logger -t logrotate "ALERT exited abnormally with [${ExitValue}]"
fi
exit 0

